import 'package:flutter/material.dart';
import 'package:flutter_html/flutter_html.dart';

class agreementDocument extends StatefulWidget {
  @override
  State<agreementDocument> createState() => _agreementDocumentState();
}

class _agreementDocumentState extends State<agreementDocument> {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: '',
      theme: new ThemeData(
        primarySwatch: Colors.amber,
      ),
      debugShowCheckedModeBanner: false,
      home: new MyHomePage(title: 'Agreement'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

const htmlData = r"""
<html>
<h1 style=\"padding-left: 111pt;text-indent: 0pt;text-align: center;\">PUCOPOINT TERMS AND CONDITIONS</h1>
<p style=\"padding-top: 9pt;padding-left: 5pt;text-indent: 0pt;text-align: left;\">EFFECTIVE FROM 23 APRIL, 2022</p>
<p style=\"text-indent: 0pt;text-align: left;\"><br /></p>
                    <p style=\"padding-left: 5pt;text-indent: 0pt;line-height: 108%;text-align: left;\"><a
                            href=\"mailto:PUCOREADS@PUCOSA.COM\" class=\"a\" target=\"_blank\"></a>IF THIS DOCUMENT IS NOT IN A LANGUAGE THAT YOU
                            UNDERSTAND, YOU SHALL CONTACT PUCOREADS AT PUCOREADS@PUCOSA.COM. FAILURE TO DO SO WITHIN 12 (TWELVE)
                        HOURS FROM THE TIME OF RECEIPT OF THIS DOCUMENT AND YOUR ACCEPTANCE OF THIS DOCUMENT BY CLICKING ON THE ‘I
                        ACCEPT’ BUTTON SHALL BE CONSIDERED AS YOUR UNDERSTANDING OF THIS DOCUMENT.</p>
                    <p style=\"text-indent: 0pt;text-align: left;\"><br /></p>
                    <h2 style=\"padding-left: 5pt;text-indent: 0pt;text-align: left;\">SUBSCRIPTION AGREEMENT</h2>
                    <p style=\"padding-top: 9pt;padding-left: 5pt;text-indent: 0pt;line-height: 108%;text-align: left;\">THIS DOCUMENT IS
                        AN ELECTRONIC RECORD IN TERMS OF INFORMATION TECHNOLOGY ACT, 2000 AND RULES THERE UNDER AS APPLICABLE AND THE
                        PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN VARIOUS STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT,
                        2000. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL
                        SIGNATURES. BY CLICKING ON THE “I ACCEPT” BUTTON ON THIS ELECTRONIC CONTRACT, YOU ARE CONSENTING TO BE BOUND BY
                        THIS SUBSCRIPTION AGREEMENT. PLEASE ENSURE THAT YOU READ AND UNDERSTAND ALL THE PROVISIONS OF THIS SUBSCRIPTION
                        AGREEMENT BEFORE YOU START USING THE PORTAL, AS YOU SHALL BE BOUND BY ALL THE TERMS HEREIN UPON CLICKING ON THE
                        “ACCEPT &amp; CONTINUE” BUTTON ON THIS ELECTRONIC CONTRACT. IF YOU DO NOT ACCEPT ANY OF THE TERMS CONTAINED
                        HEREIN, THEN PLEASE DO NOT USE THE PORTAL OR AVAIL ANY OF THE SERVICES BEING PROVIDED THEREIN. YOUR AGREEMENT TO
                        THE SUBSCRIPTION AGREEMENT SHALL OPERATE AS A BINDING AGREEMENT BETWEEN YOU AND PUCOREADS IN RESPECT OF THE
                        SERVICES OF THE PORTAL.</p>
                    <p style=\"padding-top: 7pt;padding-left: 5pt;text-indent: 0pt;line-height: 109%;text-align: left;\">THIS AGREEMENT
                        AND OTHER TERMS AND POLICIES MAY CHANGE ANYTIME WITHOUT ANY PRIOR NOTICE, SO KINDLY STAY UPDATED ABOUT OUR
                        POLICIES.</p>
                    <h2 style=\"padding-top: 7pt;padding-left: 5pt;text-indent: 0pt;text-align: left;\">DEFINITIONS</h2>
                    <p style=\"padding-top: 9pt;padding-left: 5pt;text-indent: 0pt;text-align: left;\">“You” refers to the pucopoint
                        owner.</p>
                    <p style=\"padding-top: 9pt;padding-left: 5pt;text-indent: 0pt;line-height: 109%;text-align: left;\">“Potential
                        pucopoint owner” refers to the person who has shown interest in becoming a pucopoint owner and can be the owner
                        of pucopoint in near future.</p>
                    <p style=\"padding-top: 7pt;padding-left: 5pt;text-indent: 0pt;line-height: 168%;text-align: left;\">“We, our, us,
                        company, Pucoreads” refers to the Pucoreads as a company. “Pucopoint” means the shop or place that is assigned
                        to facilitate the exchange.</p>
                    <p style=\"padding-left: 5pt;text-indent: 0pt;line-height: 107%;text-align: left;\">“Pucopoint owner” refers to the
                        owner of the pucopoint who is registered along with that pucopoint at the time of registration.</p>
                    <p style=\"padding-left: 5pt;text-indent: 0pt;line-height: 22pt;text-align: left;\">“Seller” refers to the person who
                        is selling his book and comes to pucopoint to submit the book in order. “Buyer” refers to the person who has
                        ordered the book and will be paying and collecting the book from</p>
                    <p style=\"padding-left: 5pt;text-indent: 0pt;line-height: 13pt;text-align: left;\">pucopoint.</p>
                    <h2 style=\"padding-top: 3pt;padding-left: 5pt;text-indent: 0pt;text-align: left;\">NOW THEREFORE THE PARTIES HERETO
                        AGREE AS FOLLOWS:</h2>
                    <ol id=\"l1\">
                        <li >
                            <h3 style=\"padding-top: 9pt;padding-left: 41pt;text-indent: -18pt;text-align: left;\">Scope and obligations
                            </h3>
                            <ol id=\"l2\">
                                <li >
                                    <p
                                        style=\"padding-top: 1pt;padding-left: 77pt;text-indent: -18pt;line-height: 108%;text-align: left;\">
                                        The execution of this agreement shall take effect just after the registration of Pucopoint owner
                                        on the platform. Successful registration is completed only when a potential Pucopoint owner
                                        accepts the terms on Pucopoint app.</p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 108%;text-align: left;\">We are
                                        committed to ensuring the best possible circumstances for the Pucopoints to work. Pucopoint
                                        owner needs to follow these terms to work with us. This will ensure the smooth working of the
                                        system.</p>
                                </li>
                            </ol>
                        </li>
                        <li >
                            <h3 style=\"padding-left: 41pt;text-indent: -18pt;line-height: 15pt;text-align: left;\">Behavior</h3>
                            <ol id=\"l3\">
                                <li >
                                    <p
                                        style=\"padding-top: 1pt;padding-left: 77pt;text-indent: -18pt;line-height: 107%;text-align: left;\">
                                        Pucopoint owner must keep his cool in difficult situations with customer. Pucopoint owner must
                                        not misbehave, abuse, and force any customer or our agents.</p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 108%;text-align: left;\">Pucopoint
                                        owners must not misbehave or try to compete with other Pucopoint owners. We take the
                                        responsibility to treat every Pucopoint equally and give equal opportunities to them. Any
                                        Pucopoint who is not been given equal opportunities will be those who have shown any kind of
                                        unacceptable behavior. We can take suitable actions against unacceptable behavior including
                                        suspending the partnership with Pucopoint.</p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 107%;text-align: left;\">In case of any
                                        problem, Pucopoint owner may contact us for help. We are not bound to solve every situation.
                                        Actions will be taken accordingly in certain situations.</p>
                                </li>
                            </ol>
                        </li>
                        <li >
                            <h3 style=\"padding-left: 41pt;text-indent: -18pt;text-align: left;\">Handling of Book</h3>
                            <ol id=\"l4\">
                                <li >
                                    <p
                                        style=\"padding-top: 1pt;padding-left: 77pt;text-indent: -18pt;line-height: 108%;text-align: left;\">
                                        The pucopoint owner is responsible for keeping the book safe in his custody. Books need to be
                                        delivered as it was submitted by the seller for an exchange. No of the pages should be the same
                                        during delivery of the book to the buyer as it was when the seller submitted the book.</p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 107%;text-align: left;\">In case of a
                                        return, the Pucopoint owner is responsible for delivering the unchanged book back to the seller.
                                        No of the pages, conditions, or content of the book should be the same as when the seller
                                        submitted the book before.</p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 107%;text-align: left;\">Pucopoint must
                                        not try to photocopy or scan the pages or cover of the book. Violation of this term may put
                                        Pucopoint owner in legal trouble.</p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 108%;text-align: justify;\">Pucopoint or
                                        Pucopoint owner can claim no right to the ownership of the book at any time. In case of the
                                       seller does not take the book back within 1 week from the return initiated, we will claim the
                                        ownership and take the book from the Pucopoint into our custody.</p>
                                </li>
                            </ol>
                        </li>
                        <li >
                            <h3 style=\"padding-left: 41pt;text-indent: -18pt;line-height: 15pt;text-align: justify;\">Payments</h3>
                            <ol id=\"l5\">
                                <li >
                                    <p
                                        style=\"padding-top: 1pt;padding-left: 77pt;text-indent: -18pt;line-height: 107%;text-align: left;\">
                                        Pucopoint should also facilitate the exchange of money from the buyer to us. Buyers may make the
                                        payment through online mode or cash mode.</p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 108%;text-align: left;\">Pucopoint can’t
                                        claim that money, including its commission, until we have got our share in that. Commission on
                                        every book for pucopoint will be decided by the company and will be communicated to you at the
                                        time of registration. This commission is entitled to change in the future and the same will be
                                        communicated to you when it happens.</p>
                               </li>
                                <li >
                                   <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 108%;text-align: left;\">Pucopoint owner
                                       must transfer the money to us within 4 working days. Not being able to comply with this term may
                                        force us to take necessary actions which include a fine and suspension. The suspension will only
                                        be done after three warnings to the Pucopoint</p>
                                    <p style=\"padding-top: 2pt;padding-left: 77pt;text-indent: 0pt;line-height: 107%;text-align: left;\">
                                        owner. If the Pucopoint owner fails to comply with this term after that, he may get suspended.
                                    </p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 107%;text-align: left;\">In case, the
                                        Pucopoint owner refuses to pay back the remaining money, legal action will be taken immediately.
                                    </p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 107%;text-align: left;\">Pucopoint must
                                        not use those payments for illegal activities and activities beyond the working of the company
                                        (Pucoreads).</p>
                                </li>
                            </ol>
                        </li>
                        <li >
                            <h3 style=\"padding-left: 41pt;text-indent: -18pt;text-align: left;\">Privacy</h3>
                            <ol id=\"l6\">
                                <li >
                                    <p style=\"padding-top: 1pt;padding-left: 77pt;text-indent: -18pt;text-align: left;\">Pucopoint must
                                        not disclose the identity of the seller and buyer without their consent.</p>
                                </li>
                            </ol>
                        </li>
                        <li >
                            <h3 style=\"padding-top: 1pt;padding-left: 41pt;text-indent: -18pt;text-align: left;\">Disclaimer</h3>
                            <ol id=\"l7\">
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 108%;text-align: left;\">You agree that
                                        Pucoreads manages the applications (Pucoreads and Pucopoint) and website, and is only
                                        responsible for managing them. Bad behavior of customers is not the responsibility of the
                                        company in any way.</p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 107%;text-align: left;\">You agree that
                                        you are not involved in any illegal or non-ethical activities. If this is found to be true, you
                                        agree that we can take any strict actions including suspension of the pucopoint and legal path.
                                    </p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 107%;text-align: left;\">You agree that
                                        you will comply with all the terms and conditions listed in this document. Also, you agree that
                                       you will follow our privacy policy and return policy.</p>
                                </li>
                            </ol>
                        </li>
                        <li >
                            <h3 style=\"padding-left: 41pt;text-indent: -18pt;text-align: left;\">Term and termination</h3>
                            <ol id=\"l8\">
                                <li >
                                    <p
                                        style=\"padding-top: 1pt;padding-left: 77pt;text-indent: -18pt;line-height: 109%;text-align: left;\">
                                        This Agreement shall be valid for 5 (five) years and shall be renewed automatically unless
                                        otherwise agreed between the Parties.</p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 108%;text-align: left;\">The Parties to
                                        this Agreement shall be entitled to terminate this Agreement with prior written notice of 7
                                        (seven) business days to the other Party without assigning any reason for the termination.</p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 109%;text-align: left;\">Pucoreads shall
                                        be entitled to terminate this Agreement immediately for breach of any terms in this Agreement by
                                        the Pucopoint or pucopoint owner.</p>
                                </li>
                                <li >
                                    <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 107%;text-align: left;\">Upon
                                        termination of this Agreement, the registration of Pucopoint will be terminated immediately and
                                        existing orders will be reassigned to other pucopoint.</p>
                                </li>
                            </ol>
                        </li>
                        <li >
                            <h3 style=\"padding-left: 41pt;text-indent: -18pt;text-align: left;\">Governing Law and Dispute Resolution
                            </h3>
                            <ol id=\"l9\">
                                <li >
                                    <p
                                        style=\"padding-top: 1pt;padding-left: 77pt;text-indent: -18pt;line-height: 108%;text-align: left;\">
                                        If any dispute arises between the Pucopoint owner and Pucoreads, in connection with, or arising
                                        out of, this Agreement, the dispute shall be referred to arbitration under the Arbitration and
                                        Conciliation Act, 1996 (Indian) to be adjudicated by a sole arbitrator to be appointed by
                                        Pucoreads. The proceedings of arbitration shall be in the English language. The arbitrator’s
                                        award shall be final and binding on the Parties.</p>
                                </li>
                                <li > <p style=\"padding-left: 77pt;text-indent: -18pt;line-height: 13pt;text-align: left;\">This Agreement
                                        shall be governed by and construed under the laws of India.</p>
                                </li>
                            </ol>
                        </li>
                    </ol>
                    <h2 style=\"padding-top: 9pt;padding-left: 5pt;text-indent: 0pt;text-align: left;\">Contact details:</h2>
                   <p style=\"padding-top: 9pt;padding-left: 5pt;text-indent: 0pt;line-height: 168%;text-align: left;\"><a
                            href=\"mailto:pucoreads@pucosa.com\" class=\"a\" target=\"_blank\"></a>Email: pucoreads@pucosa.com Mobile no:
        +918005189704</p>
    <p style=\"padding-left: 5pt;text-indent: 0pt;line-height: 166%;text-align: left;\">Whatsapp no: +918005189704
                        Website: pucoreads.com</p>
                </body>
                
                </html>
""";

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: AppBar(
        title: Text('Agreement'),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        child: Html(
          data: htmlData,
          tagsList: Html.tags..addAll(["bird", "flutter"]),
        ),
      ),
    );
  }
}
